version: '3.8'

services:
  analytics-api:
    build: .
    container_name: api
    env_file: ./.env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    expose:
      - "6379"
    restart: always

volumes:
  pg_data:
