version: '3.8'

services:
  analytics-api:
    build: .
    container_name: api
    env_file: ./.env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres
      - redis

  loki:
    image: LOKI:XXX
    container_name: loki
    environment:
    expose:
    volumes:

  grafana:
    image: GRAFANA:XXX
    container_name: grafana
    expose:
    restart: always

volumes: